---
- name: creer een test user
  hosts: athena
  remote_user: ansusr
  become: true
  become_user: root
  become_method: sudo
  roles:
    - name: users
      user:
        - username: frauantje      
          name: frauantje
          groups: ['adm','ansusr']
          home: /home/frauantje
    


